
spring:
  application:
    name: bag-service
  config:
    import: configserver:http://config-server:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/capstone
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  data:
    redis:
      host: redis
      port: 6379